### ISSUE TITLE
BEV camera Setting for CarlaSC dataset.

### ISSUE THREAD

**Issue by yininghase** [UMich-CURLY/3DMapping#10]
Hello, could you please provide the BEV camera Setting (for example intrinsic or extrinsic matrix) for CarlaSC dataset?

**Comment by tigeriv** [comment]
Hi, thanks for your question. The information on sensors can be found in file Data/Generation/GatherCarlaData.py. The BEV camera in specific is found at lines 96 through 105, which defines the BEV camera as:

        cameras = []
        cam_bp = blueprint_library.find('sensor.camera.rgb')
        cam_bp.set_attribute("image_size_x", str(1920))
        cam_bp.set_attribute("image_size_y", str(1080))
        cam_bp.set_attribute("fov", str(105))
        cam_location = carla.Location(0, 0, 50)
        cam_rotation = carla.Rotation(270, 0, 0)
        cam_transform = carla.Transform(cam_location, cam_rotation)
        cam01 = world.spawn_actor(cam_bp, cam_transform, attach_to=vehicle)
        cam01.listen(camera_queue.put)
        cameras.append(cam01)

More information on the sensor parameters can be found at the CARLA website here: https://carla.readthedocs.io/en/stable/cameras_and_sensors/#camera-semantic-segmentation
